name : Foundation/Jykill starter
brand : My Test Site
description : This is the description of my site
keyword: 
url : http://vulfox.github.io/jekyll-foundation-test/
imageurl: http://vulfox.github.io/jekyll-foundation-test/
email : 
twitter : DaigoFuji
github : DaigoFuji
author: Daigo Fujiwara
analytics: UA-8418273-8
year: 2014
markdown: kramdown
